# INFO0940-1 - Operating systems
# University of Liege
# Academic year 2019-2020

# Group 1
# 20161278 - MEURISSE Maxime
# 20162864 - VERMEYLEN Valentin

CC=gcc
CFLAGS=-g --pedantic -Wall -Wextra -Wmissing-prototypes -std=c99
PROGRAM=oshell

# To compile the project
all : 
	$(CC) main.c oshell.c $(CFLAGS) -o $(PROGRAM)

# To clean the workspace
clean :
	rm -f oshell
	rm -f -r oshell.dSYM
